### PR TITLE
Update to work with Laravel 5.5

### PR DESCRIPTION
**Pull request by ulc-brian**

### CODE REVIEW

**Comment by iforwms** [comment]
Any plans of merging this request?

**Comment by ghost** [comment]
@ulc-brian in addition to changing composer.json, more changes are required for compatibility.
Therefore, instead of merging this request, a new version (v3.0.0) will be released soon.

**Comment by ghost** [comment]
In addition, I will check whether changes will be required to support Laravel 5.6. If necessary, then v4.0.0 will also be released soon.

**Comment by ghost** [comment]
[Version v3.0.0](https://github.com/atehnix/laravel-stubs/releases/tag/v3.0.0) with full support for Laravel 5.5 was released.

**Pull request closed without merging**
