### PR TITLE
Update stubs.php

### PR DESCRIPTION
**Pull request by cschra**
the official Model namespace is App.
In my Opinion it makes sense to ship standard configuration first.

### CODE REVIEW

**Review by danielcamargo — COMMENTED** [review]
I am okay with defaulting to `Models` folder.

**Comment by cschra** [comment]
Sure, this is of course a matter of preference, but it shouldnt introduce Bugs, if someone would like to use the standard behaviour.
While using the package, I found, that Factories and Controllers couldn't be created without problems.
The second commit fixes the issues by checking for an empty Modelnamespace.

**Comment by ghost** [comment]
@cschra Thank you. I agree with your opinion.

A new version of the framework is coming up in the coming days.

Within a few days the package will be updated, including fixing the namespace for the models.

**Comment by ghost** [comment]
Fixed in [v5.0.0](https://github.com/atehnix/laravel-stubs/releases/tag/v5.0.0)

**Comment by cschra** [comment]
Thanks for updating, ~but I think you missed the makeController command. In the parse Model method, it should be like the factory command~.

**Comment by ghost** [comment]
Please explain what you mean.
As far as I can see, the current code of this command works correctly, both with default namespace, and with namespace "\Models".

Maybe this is only in the source code does not look like you expected, but it works correctly? ;)
Check how it actually works now.

However, it's possible that I missed something.

**Comment by cschra** [comment]
Tested it and worked, thanks a lot. Sorry for my premature reply 😅

**Pull request closed without merging**
