### PR TITLE
Add missing stubs

### PR DESCRIPTION
**Pull request by mikemand**
I'm not sure at what point they were added, but I've gone through all the locations I know of for stubs and made sure they were all here.

Edit: Thanks to GitHub's editor, I have no idea why there are so many whitespace changes...

### CODE REVIEW

**Comment by ghost** [comment]
Good job, Micheal, thanks!
Unfortunately, not all changes can be merged without changing and checking other related code.

In the coming days I will try to add support for these stubs to the package:

- controller.model.api.stub
- controller.nested.api.stub
- markdown.stub

The other three stubs that you suggested are unlikely to be useful to developers:

- event-handler.stub
- event-handler-queued.stub

Event handlers, as far as I know, are not used in the framework since Laravel version 5.1.

(By the way, it seems to me, it's time to send a PR to remove these unused stubs)

- routes.stub
This stub is used to create a route cache and there is no sense in modifying it during development.

However, thanks for the help! Thanks to you the package will be even better. :)

**Comment by mikemand** [comment]
Hi @atehnix,

The `controller.model.api.stub` works already. I created the file in `resources/stubs/` and it is being used when I generate API controllers for a model, without modifying any of the generator commands.

I was not aware Laravel had unused stubs still in it's filesystem, sorry about that.

**Comment by ghost** [comment]
Done! Released as [v6.2.0](https://github.com/atehnix/laravel-stubs/releases/tag/v6.2.0)

Thanks! =)

**Comment by mikemand** [comment]
Thanks @atehnix. 👍

**Pull request closed without merging**
